services:
  mysql:
    image: 'mysql:latest'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local